# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BikeTrackerPayload.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='BikeTrackerPayload.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x18\x42ikeTrackerPayload.proto\"\x98\x01\n\nGpsPayload\x12\x0f\n\x07gps_fix\x18\x01 \x02(\x08\x12\r\n\x05\x65poch\x18\x04 \x02(\x03\x12\x0f\n\x07\x62\x61ttery\x18\x05 \x02(\x05\x12\x10\n\x08latitude\x18\x02 \x01(\x02\x12\x11\n\tlongitude\x18\x03 \x01(\x02\x12\x11\n\tspeed_kph\x18\x06 \x01(\x02\x12\x0f\n\x07heading\x18\x07 \x01(\x02\x12\x10\n\x08\x61ltitude\x18\x08 \x01(\x02'
)




_GPSPAYLOAD = _descriptor.Descriptor(
  name='GpsPayload',
  full_name='GpsPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gps_fix', full_name='GpsPayload.gps_fix', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='epoch', full_name='GpsPayload.epoch', index=1,
      number=4, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='battery', full_name='GpsPayload.battery', index=2,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='GpsPayload.latitude', index=3,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='GpsPayload.longitude', index=4,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speed_kph', full_name='GpsPayload.speed_kph', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='heading', full_name='GpsPayload.heading', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='GpsPayload.altitude', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=181,
)

DESCRIPTOR.message_types_by_name['GpsPayload'] = _GPSPAYLOAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GpsPayload = _reflection.GeneratedProtocolMessageType('GpsPayload', (_message.Message,), {
  'DESCRIPTOR' : _GPSPAYLOAD,
  '__module__' : 'BikeTrackerPayload_pb2'
  # @@protoc_insertion_point(class_scope:GpsPayload)
  })
_sym_db.RegisterMessage(GpsPayload)


# @@protoc_insertion_point(module_scope)
